### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by YuMJie** [agoryuno/deepsolo-onnx#2]
When I run  the code copied on `deepsolo-onnx-export.ipynb` to export the  model with 
`  BACKBONE:
    NAME: "build_resnet_backbone"
`
some error occur as follow:
```
/data_local/deepsolo/deepsolo-onnx/DeepSolo/adet/modeling/model/detection_transformer.py:221: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference.shape[-1] == 2:
/data_local/deepsolo/deepsolo-onnx/DeepSolo/adet/modeling/model/detection_transformer.py:271: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for a, b, c, d in zip(outputs_class[:-1], outputs_text[:-1], outputs_coord[:-1], outputs_bd_coord[:-1])
Segmentation fault (core dumped)
```

the code is as follow
```
import os
import shutil
from DeepSolo.onnx_model import SimpleONNXReadyModel
import numpy as np
CHECKPOINT = "/result/R50/150k_tt_mlt_13_15/finetune/ic15/model_final.pth"
OUTPATH = "/result/R50/150k_tt_mlt_13_15/finetune/ic15/deepsolo.onnx"
DIMS = (512,512)
CONFIG = "configs/Base_det_export_R5.yaml"
CHANNELS = 3
model = SimpleONNXReadyModel(CONFIG, CHECKPOINT)
img = np.random.randint(0, 255, (CHANNELS, *DIMS))
img = img.astype(np.int8)
import torch.onnx
import torch
img_t = torch.from_numpy(img)
torch.onnx.export(model.model,
           [img_t],
           OUTPATH,
           export_params=True,
           do_constant_folding=True, opset_version=11)
```

**Comment by shining-love** [comment]
Base_det_export_R5.yaml，release

**Comment by shining-love** [comment]
> When I run the code copied on `deepsolo-onnx-export.ipynb` to export the model with ` BACKBONE: NAME: "build_resnet_backbone"` some error occur as follow:
> 
> ```
> /data_local/deepsolo/deepsolo-onnx/DeepSolo/adet/modeling/model/detection_transformer.py:221: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if reference.shape[-1] == 2:
> /data_local/deepsolo/deepsolo-onnx/DeepSolo/adet/modeling/model/detection_transformer.py:271: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
>   for a, b, c, d in zip(outputs_class[:-1], outputs_text[:-1], outputs_coord[:-1], outputs_bd_coord[:-1])
> Segmentation fault (core dumped)
> ```
> 
> the code is as follow
> 
> ```
> import os
> import shutil
> from DeepSolo.onnx_model import SimpleONNXReadyModel
> import numpy as np
> CHECKPOINT = "/result/R50/150k_tt_mlt_13_15/finetune/ic15/model_final.pth"
> OUTPATH = "/result/R50/150k_tt_mlt_13_15/finetune/ic15/deepsolo.onnx"
> DIMS = (512,512)
> CONFIG = "configs/Base_det_export_R5.yaml"
> CHANNELS = 3
> model = SimpleONNXReadyModel(CONFIG, CHECKPOINT)
> img = np.random.randint(0, 255, (CHANNELS, *DIMS))
> img = img.astype(np.int8)
> import torch.onnx
> import torch
> img_t = torch.from_numpy(img)
> torch.onnx.export(model.model,
>            [img_t],
>            OUTPATH,
>            export_params=True,
>            do_constant_folding=True, opset_version=11)
> ```

Base_det_export_R5.yaml，release

**Comment by stevenLuzhengti** [comment]
@shining-love Could please share Base_det_export_R5.yaml for me? I want to have a quick test, thanks !

**Comment by YuMJie** [comment]
The file `Base_det_export_R5.yaml ` is on deepsolo official code. which is in ` https://github.com/ViTAE-Transformer/DeepSolo/blob/main/configs/**<dataset>**/Base_det.yaml` . Note : <dataset> is the dataset you run on .

**Comment by stevenLuzhengti** [comment]
@YuMJie 
Thank you so much, I know what to do now. Also, I saw you mentioned a segmentation fault issue—did you ever resolve that? I've been struggling with this problem and I'm not sure if it's due to my PyTorch version or something else,I urgently need your help.

**Comment by YuMJie** [comment]
@stevenLuzhengti 
Yes, the problem is related to the pytorch version, but I forget which pytorch version I use. I remember that the pytorch version of deepsolo-onnx is different from the official version used by deepsolo, you can try the latest version, or torch 1.13.1.

**Comment by stevenLuzhengti** [comment]
@YuMJie 

Thank you very much for your prompt response. I'm currently using a similar package setup as you, specifically PyTorch 2.1.0 cu118, and I have read your discussions in deepsolo. You were using PyTorch 2.0.1, but I don't think the version difference is what's affecting me. My issue is with the official deepsolo-onnx release of ViTAE-s, which completely fails for me, still resulting in a segmentation fault. However, when using the R50 network directly from the release, I encounter a different error as shown below:
`Traceback (most recent call last):
  File "/home/ubuntu/workspace/projects/evaluate/texspotting/deepsolo-onnx/content/convert2onnx.py", line 53, in <module>
    torch.onnx.export(model,
  File "/usr/local/lib/python3.9/dist-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/usr/local/lib/python3.9/dist-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.9/dist-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.9/dist-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.9/dist-packages/torch/jit/_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/jit/_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.9/dist-packages/torch/jit/_trace.py", line 127, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: Instances
`

My question pertains to the error above. 
1. Do you encounter this error with the official R50? 
2. Can you successfully convert the ViTAE-s released by deepsolo-onnx into ONNX? 


Additionally, may I add you on WeChat for convenience?

Thank you so much

BTW pytroch 1.13.1 is not suitable since a package called 'Compile' needed for pytorch

**Comment by YuMJie** [comment]
@stevenLuzhengti Yes, I remember that it was probably because the torch version or cuda was wrong, because I was able to work after changing the version, and for some reason I stopped working on the project, so I couldn't provide you with the code. Still, I think you can check the version of onnx. I haven't had any problems with ViTAE-s either, probably because of the type of input. Hope it helps you

**Comment by stevenLuzhengti** [comment]
@YuMJie 
Thank you very much for your help. I believe I should be able to solve this problem. If you manage to get it done, I have two final questions:

1. Have you converted both R50 and ViTAWE-s to ONNX and tested them successfully, and the inference is correct?
2. Have you tested them on the TensorRT platform or any other platforms? How is the speed?

**Comment by YuMJie** [comment]
@stevenLuzhengti 
 1. Yes, I successfully converted onnx and verified that the result is correct, however, the code I provided above only supports the input of fixed dimensions, and it is better to use dynamic dimensions in actual scenarios, which requires you to modify the code of the model, which took a few days to modify.
2. I didn't test on these platforms. At that time, it was simply inference, and I personally felt that the speed was not very fast, because the model was very large.

**Comment by stevenLuzhengti** [comment]
I think the speed should be acceptable. From an architectural perspective, In R50, ResNet has already extracted the lower-level features. If we use INT8 quantization, it shouldn't be too slow. Additionally, the accuracy of DeepSolo is really good. I trained this network and found its performance to be quite impressive, surpassing other solutions I've seen so far.

**Comment by stevenLuzhengti** [comment]
@YuMJie 
Thank you very much, and sorry for bothering you again. As you mentioned, if the versions of PyTorch, Python, and CUDA are installed correctly, it is possible to successfully convert to the new ONNX model without encountering a segmentation fault. However, after the conversion, my output does not match the output from the PyTorch model. I wanted to ask, did you use the code directly from Deep Solo for the conversion? Do you remember making any modifications to the code?

**Comment by YuMJie** [comment]
@stevenLuzhengti 
I remember that need to modify the image **pre-processing** and **post-processing** parts, you can see if the tensors of pytorch and onnx into the model **after image processing** are the same, by the way, you can first make the image input by **onnx export** the same as the image of **pytorch**, make sure they output the same result.

**Comment by stevenLuzhengti** [comment]
@YuMJie Thank you very much for your help. I'm still struggling with the accuracy of the outputs, and I tried your methods Currently, for the first network, such as ResNet50, my output has a difference of 0.0003 between PyTorch and ONNX,

**Comment by YuMJie** [comment]
@stevenLuzhengti Onnx and PyTorch will be a little different, 0.0003 is the acceptable range of error

**Comment by stevenLuzhengti** [comment]
@YuMJie  Hey thanks for your help, I think I made some progress now, I'm curious about how you were able to successfully convert your model to ONNX. Yesterday, I found that after converting my model to ONNX, the internal C++ operator （deformaaltransformer） was transformed into an all-zero matrix. You can see this in the image below(MatMul node). It might be that your ONNX environment is different from mine. If you have a correctly converted ONNX model, could you send me a copy to check?

![image](https://github.com/agoryuno/deepsolo-onnx/assets/126463744/a601c8b1-15d5-4fd2-a4e9-12f76cf03822)

![image](https://github.com/agoryuno/deepsolo-onnx/assets/126463744/db159a6a-635c-49d8-a545-ddff8e09b2dd)

**Comment by YuMJie** [comment]
@stevenLuzhengti could you share your email ?

**Comment by stevenLuzhengti** [comment]
@YuMJie stevenluzheng.uk@gmail.com thanks so much!
